
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[424] =
    {   0,
       83,   83,   87,   85,   83,   84,   33,   38,   32,   39,
        9,   12,   36,   34,   16,   35,   17,   37,   81,   21,
       15,   18,   20,   19,   82,   82,   82,   82,   82,   82,
       82,   11,   14,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       10,   31,   13,   83,   30,   25,   27,   23,   28,   24,
       81,   26,    0,   81,   22,   82,    0,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,    1,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   29,    0,    0,   82,   61,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,    5,   82,   82,   42,
       82,   82,   82,   82,   82,   82,   82,   33,   82,   50,
       82,   82,   82,   82,   82,   82,   82,    0,   82,    0,
       82,   52,   82,   82,   82,   82,   82,   82,    7,   82,
       82,   82,   82,   82,    2,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   46,   82,   82,   82,
       82,   82,   82,   73,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,

       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,    4,   82,   57,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,    3,   82,   82,   82,   82,   82,
       82,   82,   82,   62,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,    6,   82,   68,
       82,   82,   82,   82,   82,   82,   82,   82,    8,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   66,   82,   82,   82,   82,   64,

       82,   82,   82,   82,   82,   79,   82,   82,   82,   82,
       82,   82,   82,   78,   82,   59,   82,   82,   80,   82,
       82,   82,   70,   40,   74,   82,   55,   82,   82,   82,
       54,   82,   82,   82,   82,   82,   75,   44,   45,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   67,   47,   82,   82,   82,   82,
       82,   69,   82,   82,   82,   82,   82,   43,   51,   82,
       82,   82,   82,   82,   82,   58,   82,   82,   53,   48,
       82,   82,   82,   82,   82,   82,   82,   65,   82,   82,
       82,   82,   82,   82,   82,   82,   72,   82,   82,   82,

       82,   63,   82,   82,   71,   82,   82,   82,   82,   82,
       49,   76,   82,   82,   56,   82,   77,   41,   82,   82,
       82,   60,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   26,   25,   25,   25,
       25,   25,   25,   27,   25,   28,   29,   25,   25,   30,
       25,   25,   31,   25,   25,   25,   25,   25,   25,   25,
       32,    1,   33,    1,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    3,    3,    3,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    3,
        3,    4,    5,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[427] =
    {   0,
        0,    0,  843,  844,  840,  844,  844,  844,  835,  844,
      844,  844,  817,   53,  844,   52,   50,  816,   63,  844,
      844,  844,  815,  844,  805,   38,   39,   40,   46,   41,
       54,  844,  844,   55,   57,   62,   66,   64,   67,   79,
       74,   68,  102,   89,   90,   71,   83,   94,   97,  100,
      844,  774,  844,  833,  844,  844,  844,  844,  844,  844,
      136,  844,  140,  146,  844,  802,  149,  115,  104,   42,
      129,  137,   99,  139,  140,  141,  142,  143,  148,  150,
      149,  151,  105,  152,   98,  155,  801,  159,  156,  164,
      171,  167,  168,  174,  175,  176,  178,  180,  179,  181,

      182,  188,  185,  191,  193,  844,  221,  799,  192,  799,
      187,  197,  210,  209,  212,  211,  218,  219,  217,  220,
      228,  227,  231,  232,  235,  229,  798,  238,  241,  797,
      242,  243,  245,  246,  248,  249,  255,  796,  252,  795,
      254,  253,  263,  264,  265,  267,  269,  290,  794,  792,
      268,  792,  272,  280,  279,  281,  284,  271,  791,  288,
      293,  294,  298,  299,  300,  301,  303,  312,  305,  307,
      309,  313,  323,  322,  329,  331,  790,  330,  332,  314,
      341,  333,  339,  789,  340,  348,  342,  343,  345,  346,
      354,  356,  358,  359,  360,  363,  362,  366,  370,  373,

      372,  378,  380,  379,  383,  381,  384,  385,  388,  389,
      391,  395,  398,  404,  405,  406,  407,  410,  411,  413,
      415,  788,  414,  787,  416,  421,  417,  418,  422,  427,
      419,  429,  430,  436,  786,  438,  443,  444,  448,  450,
      446,  451,  454,  785,  455,  456,  457,  459,  464,  458,
      466,  469,  470,  475,  476,  478,  479,  784,  483,  783,
      482,  486,  485,  490,  487,  498,  488,  497,  782,  501,
      489,  507,  502,  510,  511,  508,  516,  518,  519,  520,
      522,  523,  524,  526,  528,  529,  530,  531,  532,  533,
      542,  536,  537,  544,  781,  543,  546,  553,  552,  780,

      555,  560,  561,  562,  566,  779,  568,  569,  570,  571,
      572,  575,  574,  778,  573,  777,  578,  583,  776,  586,
      590,  587,  775,  774,  773,  591,  772,  592,  593,  594,
      771,  596,  606,  608,  602,  607,  770,  769,  768,  612,
      613,  615,  620,  621,  617,  624,  622,  627,  628,  630,
      639,  633,  641,  631,  766,  759,  648,  649,  650,  651,
      653,  758,  654,  655,  661,  663,  664,  757,  756,  665,
      666,  668,  669,  671,  672,  755,  674,  673,  754,  753,
      632,  676,  683,  688,  689,  679,  687,  750,  691,  692,
      697,  698,  699,  700,  703,  706,  748,  704,  712,  713,

      715,  742,  717,  718,  741,  720,  721,  726,  722,  727,
      739,  738,  725,  728,  736,  730,  270,  112,  729,  731,
      733,   70,  844,  791,   98,  794
    } ;

static yyconst flex_int16_t yy_def[427] =
    {   0,
      423,    1,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  424,  424,  424,  424,  424,  424,
      424,  423,  423,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  424,  425,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  423,  423,  426,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  423,  423,  426,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,    0,  423,  423,  423
    } ;

static yyconst flex_uint16_t yy_nxt[908] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   19,   19,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   25,   34,   35,   36,   37,   38,   39,
       40,   25,   41,   42,   25,   43,   44,   45,   25,   46,
       25,   47,   48,   49,   25,   25,   50,   25,   25,   25,
       51,   52,   53,   57,   59,   61,   61,   61,   61,   67,
       67,   67,   67,   67,   60,   58,   63,   67,   64,   64,
       64,   64,   70,   68,   71,   67,   67,   69,   67,  111,
       73,   76,   72,   67,   74,   67,   77,   67,   67,   67,

      108,   67,   67,   78,   80,   67,   75,   79,   81,   82,
       67,   83,   84,   87,   67,   85,   89,   86,   90,   91,
       67,   67,   97,   93,   95,   67,   88,   94,   67,   67,
       67,   67,   99,   67,  104,   67,   67,   98,   96,  110,
      114,  105,  125,   67,   92,  103,   67,  100,  101,  127,
      102,   61,   61,   61,   61,   61,   61,   61,   61,   63,
       67,   64,   64,   64,   64,  107,  107,  107,   67,  109,
       67,   67,   67,   67,   67,  112,  116,  119,  115,   67,
       67,   67,   67,   67,  121,  113,   67,   67,  117,  122,
       67,  131,  129,  130,  118,   67,  120,  132,   67,   67,

      126,  123,   67,  124,  133,   67,   67,   67,  128,   67,
       67,   67,   67,   67,  134,  142,   67,  143,   67,   67,
      136,  137,   67,   67,   67,  135,  139,  140,   67,  138,
      144,  152,  141,  146,  145,  147,  148,  148,  148,  148,
       67,   67,   67,   67,  151,  153,  154,  155,   67,   67,
       67,   67,  157,  149,  156,  158,  161,  159,   67,   67,
       67,  163,   67,   67,  160,  162,   67,  164,  166,   67,
      165,  168,   67,   67,   67,  170,   67,   67,  167,   67,
       67,  174,  175,   67,   67,   67,   67,  179,  178,  171,
      173,  172,  169,  177,   67,   67,   67,  176,   67,   67,

       67,   67,   67,   67,  180,  148,  148,  148,  148,  181,
       67,   67,   67,  183,  185,   67,  189,  182,  188,   67,
      184,  186,  149,  187,   67,   67,  191,  192,  190,   67,
       67,   67,   67,  197,   67,  193,   67,  194,   67,  195,
       67,  206,  198,   67,   67,   67,  201,  208,  202,  207,
      199,  209,  196,   67,   67,  200,  210,  203,  204,  205,
       67,   67,   67,   67,   67,  211,  216,  218,  215,  220,
       67,   67,   67,   67,   67,  217,   67,   67,  222,   67,
      212,  213,  214,  219,  221,   67,  223,   67,  227,   67,
       67,   67,  231,   67,   67,  225,  230,   67,  229,  226,

      224,   67,  232,   67,   67,  235,  237,  228,  233,   67,
       67,   67,   67,  234,   67,   67,   67,  241,  236,   67,
       67,  244,   67,  239,  247,  248,   67,  238,  240,   67,
      242,  245,  243,  250,  246,   67,   67,   67,   67,  249,
      251,   67,   67,  256,   67,   67,   67,   67,   67,   67,
       67,  254,   67,   67,  258,  255,  264,  253,   67,  265,
       67,   67,  252,  259,  257,  260,  262,   67,  261,   67,
      263,  267,  266,  270,   67,   67,  268,   67,  273,   67,
      271,   67,   67,  269,  275,   67,   67,   67,   67,   67,
       67,  281,  276,  282,  272,   67,  274,   67,  277,  283,

       67,   67,  286,  279,  280,  278,   67,   67,  284,   67,
       67,  289,  291,   67,   67,  288,   67,   67,   67,   67,
       67,   67,  287,  292,  294,  285,  296,  290,   67,   67,
      293,  298,   67,   67,  301,  300,  302,  299,   67,   67,
      297,   67,   67,  295,  304,  303,  305,   67,  306,   67,
       67,   67,  309,   67,   67,   67,  307,   67,  308,   67,
       67,   67,   67,   67,   67,  320,  316,   67,   67,  312,
      310,  311,  313,   67,   67,   67,  314,   67,  318,  319,
      315,  321,  317,   67,   67,  322,   67,  327,  324,  328,
      329,   67,   67,   67,  323,  325,  326,   67,  330,   67,

       67,   67,   67,   67,   67,   67,   67,  333,  341,   67,
      334,  332,  340,  331,   67,  342,  336,   67,   67,  335,
      345,   67,   67,   67,   67,   67,  349,   67,  337,  338,
      339,  350,  346,   67,  344,  347,  343,   67,   67,   67,
      353,  354,  351,   67,   67,  348,   67,  356,   67,  358,
      352,   67,   67,   67,  361,   67,  363,  365,   67,   67,
      355,   67,   67,   67,   67,  391,  359,  368,  357,  360,
       67,  364,   67,  362,  369,  370,  371,  367,  366,   67,
       67,   67,   67,  372,   67,   67,   67,  377,  375,  376,
      373,  374,   67,  378,   67,   67,   67,   67,  382,   67,

       67,  381,   67,   67,   67,   67,  386,   67,  379,  388,
       67,  384,  392,  380,   67,  390,  383,  385,   67,   67,
       67,  393,   67,   67,  387,  389,  394,  395,   67,   67,
       67,   67,  396,  403,   67,   67,  402,   67,  406,  399,
      401,  404,  398,   67,   67,  397,   67,  405,   67,   67,
      400,   67,   67,   67,  407,  411,   67,   67,   67,   67,
       67,   67,   67,  410,   67,  416,  418,   67,  409,   67,
       67,  408,   67,   67,  413,  414,  419,  420,  412,   67,
      415,   67,  421,  417,   67,   67,   67,   67,   67,   67,
       67,  422,   66,   66,   66,  150,  150,   67,  150,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,  149,   67,   67,   67,   67,   67,
       67,  149,   67,   67,   54,  106,   67,   65,   62,   56,
       55,   54,  423,    3,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423
    } ;

static yyconst flex_int16_t yy_chk[908] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   14,   16,   17,   17,   17,   17,   26,
       27,   28,   30,   70,   16,   14,   19,   29,   19,   19,
       19,   19,   28,   26,   29,   31,   34,   27,   35,   70,
       31,   35,   30,   36,   34,   38,   36,   37,   39,   42,

      425,  422,   46,   36,   37,   41,   34,   36,   37,   38,
       40,   38,   39,   41,   47,   39,   42,   40,   43,   43,
       44,   45,   46,   44,   45,   48,   41,   44,   49,   85,
       73,   50,   48,   43,   50,   69,   83,   47,   45,   69,
       73,   50,   83,  418,   43,   49,   68,   48,   48,   85,
       48,   61,   61,   61,   61,   63,   63,   63,   63,   64,
       71,   64,   64,   64,   64,   67,   67,   67,   72,   68,
       74,   75,   76,   77,   78,   71,   75,   78,   74,   79,
       81,   80,   82,   84,   80,   72,   86,   89,   76,   80,
       88,   89,   88,   88,   77,   90,   79,   90,   92,   93,

       84,   81,   91,   82,   91,   94,   95,   96,   86,   97,
       99,   98,  100,  101,   92,  100,  103,  101,  111,  102,
       94,   95,  104,  109,  105,   93,   97,   98,  112,   96,
      102,  111,   99,  104,  103,  105,  107,  107,  107,  107,
      114,  113,  116,  115,  109,  112,  113,  114,  119,  117,
      118,  120,  116,  107,  115,  117,  120,  118,  122,  121,
      126,  122,  123,  124,  119,  121,  125,  123,  125,  128,
      124,  128,  129,  131,  132,  131,  133,  134,  126,  135,
      136,  135,  136,  139,  142,  141,  137,  141,  139,  132,
      134,  133,  129,  137,  143,  144,  145,  136,  146,  151,

      147,  417,  158,  153,  142,  148,  148,  148,  148,  143,
      155,  154,  156,  145,  147,  157,  155,  144,  154,  160,
      146,  151,  148,  153,  161,  162,  157,  158,  156,  163,
      164,  165,  166,  164,  167,  160,  169,  161,  170,  162,
      171,  170,  165,  168,  172,  180,  168,  171,  168,  170,
      166,  172,  163,  174,  173,  167,  173,  168,  168,  169,
      175,  178,  176,  179,  182,  174,  179,  180,  178,  182,
      183,  185,  181,  187,  188,  179,  189,  190,  185,  186,
      175,  175,  176,  181,  183,  191,  186,  192,  190,  193,
      194,  195,  194,  197,  196,  188,  193,  198,  192,  189,

      187,  199,  195,  201,  200,  198,  200,  191,  196,  202,
      204,  203,  206,  197,  205,  207,  208,  204,  199,  209,
      210,  207,  211,  202,  210,  210,  212,  201,  203,  213,
      205,  208,  206,  212,  209,  214,  215,  216,  217,  211,
      213,  218,  219,  218,  220,  223,  221,  225,  227,  228,
      231,  216,  226,  229,  220,  217,  228,  215,  230,  229,
      232,  233,  214,  221,  219,  223,  226,  234,  225,  236,
      227,  231,  230,  234,  237,  238,  232,  241,  238,  239,
      236,  240,  242,  233,  240,  243,  245,  246,  247,  250,
      248,  247,  241,  248,  237,  249,  239,  251,  242,  249,

      252,  253,  252,  245,  246,  243,  254,  255,  250,  256,
      257,  255,  257,  261,  259,  254,  263,  262,  265,  267,
      271,  264,  253,  259,  262,  251,  264,  256,  268,  266,
      261,  266,  270,  273,  270,  268,  271,  267,  272,  276,
      265,  274,  275,  263,  273,  272,  274,  277,  275,  278,
      279,  280,  278,  281,  282,  283,  276,  284,  277,  285,
      286,  287,  288,  289,  290,  289,  285,  292,  293,  281,
      279,  280,  282,  291,  296,  294,  283,  297,  287,  288,
      284,  290,  286,  299,  298,  291,  301,  297,  293,  298,
      299,  302,  303,  304,  292,  294,  296,  305,  301,  307,

      308,  309,  310,  311,  315,  313,  312,  304,  313,  317,
      305,  303,  312,  302,  318,  315,  308,  320,  322,  307,
      320,  321,  326,  328,  329,  330,  328,  332,  309,  310,
      311,  329,  321,  335,  318,  322,  317,  333,  336,  334,
      333,  334,  330,  340,  341,  326,  342,  336,  345,  341,
      332,  343,  344,  347,  344,  346,  345,  347,  348,  349,
      335,  350,  354,  381,  352,  381,  342,  350,  340,  343,
      351,  346,  353,  344,  351,  352,  353,  349,  348,  357,
      358,  359,  360,  354,  361,  363,  364,  361,  359,  360,
      357,  358,  365,  363,  366,  367,  370,  371,  367,  372,

      373,  366,  374,  375,  378,  377,  373,  382,  364,  375,
      386,  371,  382,  365,  383,  378,  370,  372,  387,  384,
      385,  383,  389,  390,  374,  377,  384,  385,  391,  392,
      393,  394,  386,  394,  395,  398,  393,  396,  398,  390,
      392,  395,  389,  399,  400,  387,  401,  396,  403,  404,
      391,  406,  407,  409,  399,  404,  413,  408,  410,  414,
      419,  416,  420,  403,  421,  410,  414,  415,  401,  412,
      411,  400,  405,  402,  407,  408,  416,  419,  406,  397,
      409,  388,  420,  413,  380,  379,  376,  369,  368,  362,
      356,  421,  424,  424,  424,  426,  426,  355,  426,  339,

      338,  337,  331,  327,  325,  324,  323,  319,  316,  314,
      306,  300,  295,  269,  260,  258,  244,  235,  224,  222,
      184,  177,  159,  152,  150,  149,  140,  138,  130,  127,
      110,  108,   87,   66,   54,   52,   25,   23,   18,   13,
        9,    5,    3,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[87] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexfinal.lex"
#line 2 "lexfinal.lex"
	#include "utility2.cpp"
	#include "bisonfinal.tab.h"
	using namespace std;
	void yyerror(char *s);
	extern "C" int yywrap() { }
	int lineno = 1;
#line 842 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 13 "lexfinal.lex"

#line 1062 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 424 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 844 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "lexfinal.lex"
{ yylval.Node = add_leaf("IF","if"); printf("Found %s\n", yytext); return IF;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "lexfinal.lex"
{ yylval.Node = add_leaf("ELSE","else"); printf("Found %s\n", yytext); return ELSE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 16 "lexfinal.lex"
{ yylval.Node = add_leaf("ELSEIF","elseif"); printf("Found %s\n", yytext); return ELSEIF; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 17 "lexfinal.lex"
{ yylval.Node = add_leaf("WHILE","while"); printf("Found %s\n", yytext); return WHILE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 18 "lexfinal.lex"
{ yylval.Node = add_leaf("FOR","for"); printf("Found %s\n", yytext); return FOR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 19 "lexfinal.lex"
{ yylval.Node = add_leaf("SWITCH","switch"); printf("Found %s\n", yytext); return SWITCH;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 20 "lexfinal.lex"
{ yylval.Node = add_leaf("CASE","case"); printf("Found %s\n", yytext); return CASE;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 21 "lexfinal.lex"
{ yylval.Node = add_leaf("DEFAULT","default"); printf("Found %s\n", yytext); return DEFAULT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 22 "lexfinal.lex"
{ yylval.Node = add_leaf("LP","("); printf("Found %s\n", yytext); return LP ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 23 "lexfinal.lex"
{ yylval.Node = add_leaf("LCP", "{"); printf("Found %s\n", yytext); return LCP; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "lexfinal.lex"
{ yylval.Node = add_leaf("LSP", "["); printf("Found %s\n", yytext); return LSP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "lexfinal.lex"
{ yylval.Node = add_leaf("RP",")"); printf("Found %s\n", yytext); return RP ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "lexfinal.lex"
{ yylval.Node = add_leaf("RCP","}"); printf("Found %s\n", yytext); return RCP;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "lexfinal.lex"
{ yylval.Node = add_leaf("RSP","]"); printf("Found %s\n", yytext); return RSP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "lexfinal.lex"
{ yylval.Node = add_leaf("SEMI",";"); printf("Found %s\n", yytext); return SEMI;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "lexfinal.lex"
{ yylval.Node = add_leaf("COMMA",","); printf("Found %s\n", yytext); return COMMA ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "lexfinal.lex"
{ yylval.Node = add_leaf("DOT","."); printf("Found %s\n", yytext); return DOT ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "lexfinal.lex"
{ yylval.Node = add_leaf("LT","<"); printf("Found %s\n", yytext); return LT ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "lexfinal.lex"
{ yylval.Node = add_leaf("GT",">"); printf("Found %s\n", yytext); return GT ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "lexfinal.lex"
{ yylval.Node = add_leaf("EQ","="); printf("Found %s\n", yytext); return EQ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "lexfinal.lex"
{ yylval.Node = add_leaf("COLON",":"); printf("Found %s\n", yytext); return COLON ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "lexfinal.lex"
{ yylval.Node = add_leaf("EQEQ","=="); printf("Found %s\n", yytext); return EQEQ; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "lexfinal.lex"
{ yylval.Node = add_leaf("PLUSEQ","+="); printf("Found %s\n", yytext); return PLUSEQ; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "lexfinal.lex"
{ yylval.Node = add_leaf("MINUSEQ","-="); printf("Found %s\n", yytext); return MINUSEQ;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "lexfinal.lex"
{ yylval.Node = add_leaf("MULTIPLYEQ","*="); printf("Found %s\n", yytext); return MULTIPLYEQ;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "lexfinal.lex"
{ yylval.Node = add_leaf("DIVIDEEQ","/="); printf("Found %s\n", yytext); return DIVIDEEQ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "lexfinal.lex"
{ yylval.Node = add_leaf("PLUSPLUS","++"); printf("Found %s\n", yytext); return PLUSPLUS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "lexfinal.lex"
{ yylval.Node = add_leaf("MINUSMINUS","--"); printf("Found %s\n", yytext); return MINUSMINUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 42 "lexfinal.lex"
{ yylval.Node = add_leaf("OR","||"); printf("Found %s\n", yytext); return OR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 43 "lexfinal.lex"
{ yylval.Node = add_leaf("AND","&&"); printf("Found %s\n", yytext); return AND;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 44 "lexfinal.lex"
{ yylval.Node = add_leaf("BITOR","|"); printf("Found %s\n", yytext); return BITOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 45 "lexfinal.lex"
{ yylval.Node = add_leaf("BITAND","&"); printf("Found %s\n", yytext); return BITAND; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 46 "lexfinal.lex"
{ yylval.Node = add_leaf("NOT","not"); printf("Found %s\n", yytext); return NOT ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 47 "lexfinal.lex"
{ yylval.Node = add_leaf("PLUS","+"); printf("Found %s\n", yytext); return PLUS ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 48 "lexfinal.lex"
{ yylval.Node = add_leaf("MINUS","-"); printf("Found %s\n", yytext); return MINUS ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 49 "lexfinal.lex"
{ yylval.Node = add_leaf("MULTIPLY","*"); printf("Found %s\n", yytext); return MULTIPLY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 50 "lexfinal.lex"
{ yylval.Node = add_leaf("DIVIDE","/"); printf("Found %s\n", yytext); return DIVIDE ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 51 "lexfinal.lex"
{ yylval.Node = add_leaf("DQUOTE","\""); printf("Found %s\n", yytext); return DQUOTE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 52 "lexfinal.lex"
{ yylval.Node = add_leaf("SQUOTE","'"); printf("Found %s\n", yytext); return SQUOTE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 53 "lexfinal.lex"
{ yylval.Node = add_leaf("PROCESSOR","Processor"); printf("Found %s\n", yytext); return PROCESSOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 54 "lexfinal.lex"
{ yylval.Node = add_leaf("ARCHITECTURE_TYPE","architecture_type"); printf("Found %s\n", yytext); return ARCHITECTURE_TYPE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 55 "lexfinal.lex"
{ yylval.Node = add_leaf("ISA","isa"); printf("Found %s\n", yytext); return ISA;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 56 "lexfinal.lex"
{ yylval.Node = add_leaf("CLOCK_SPEED","clock_speed"); printf("Found %s\n", yytext); return CLOCK_SPEED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 57 "lexfinal.lex"
{ yylval.Node = add_leaf("L1_MEMORY","l1_memory"); printf("Found %s\n", yytext); return L1_MEMORY ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 58 "lexfinal.lex"
{ yylval.Node = add_leaf("L2_MEMORY","l2_memory"); printf("Found %s\n", yytext); return L2_MEMORY ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 59 "lexfinal.lex"
{ yylval.Node = add_leaf("NAME","name"); printf("Found %s\n", yytext); return NAME ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 60 "lexfinal.lex"
{ yylval.Node = add_leaf("IS_RUNNING","is_running"); printf("Found %s\n", yytext); return IS_RUNNING ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 61 "lexfinal.lex"
{ yylval.Node = add_leaf("SUBMIT_JOBS","submit_jobs"); printf("Found %s\n", yytext); return SUBMIT_JOBS; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 62 "lexfinal.lex"
{ yylval.Node = add_leaf("GET_CLOCK_SPEED","get_clock_speed"); printf("Found %s\n", yytext); return GET_CLOCK_SPEED ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 63 "lexfinal.lex"
{ yylval.Node = add_leaf("RUN","run"); printf("Found %s\n", yytext); return RUN ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 64 "lexfinal.lex"
{ yylval.Node = add_leaf("DISCARD_JOB","discard_job"); printf("Found %s\n", yytext); return DISCARD_JOB ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 65 "lexfinal.lex"
{ yylval.Node = add_leaf("LINK","Link"); printf("Found %s\n", yytext); return LINK ;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 66 "lexfinal.lex"
{ yylval.Node = add_leaf("START_POINT","start_point"); printf("Found %s\n", yytext); return START_POINT ; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "lexfinal.lex"
{ yylval.Node = add_leaf("END_POINT","end_point"); printf("Found %s\n", yytext); return END_POINT ;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 68 "lexfinal.lex"
{ yylval.Node = add_leaf("BANDWIDTH","bandwidth"); printf("Found %s\n", yytext); return BANDWIDTH ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 69 "lexfinal.lex"
{ yylval.Node = add_leaf("CHANNEL_CAPACITY","channel_capacity"); printf("Found %s\n", yytext); return CHANNEL_CAPACITY ;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 70 "lexfinal.lex"
{ yylval.Node = add_leaf("MEMORY","memory"); printf("Found %s\n", yytext); return MEMORY ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 71 "lexfinal.lex"
{ yylval.Node = add_leaf("MEMORY_TYPE","memory_type"); printf("Found %s\n", yytext); return MEMORY_TYPE ;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "lexfinal.lex"
{ yylval.Node = add_leaf("MEM_SIZE","mem_size"); printf("Found %s\n", yytext); return MEM_SIZE ; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 73 "lexfinal.lex"
{ yylval.Node = add_leaf("GET_AVAILABLE_MEMORY","get_available_memory"); printf("Found %s\n", yytext); return GET_AVAILABLE_MEMORY ;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 74 "lexfinal.lex"
{ yylval.Node = add_leaf("JOB","job"); printf("Found %s\n", yytext); return JOB ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 75 "lexfinal.lex"
{ yylval.Node = add_leaf("JOB_ID","job_id"); printf("Found %s\n", yytext); return JOB_ID ; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 76 "lexfinal.lex"
{ yylval.Node = add_leaf("FLOPS_REQUIRED","flops_required"); printf("Found %s\n", yytext); return FLOPS_REQUIRED ; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 77 "lexfinal.lex"
{ yylval.Node = add_leaf("DEADLINE","deadline"); printf("Found %s\n", yytext); return DEADLINE ;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 78 "lexfinal.lex"
{ yylval.Node = add_leaf("MEM_REQUIRED","mem_required"); printf("Found %s\n", yytext); return MEM_REQUIRED ;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 79 "lexfinal.lex"
{ yylval.Node = add_leaf("AFFINITY","affinity"); printf("Found %s\n", yytext); return AFFINITY ;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 80 "lexfinal.lex"
{ yylval.Node = add_leaf("GET_MEMORY","get_memory"); printf("Found %s\n", yytext); return GET_MEMORY ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 81 "lexfinal.lex"
{ yylval.Node = add_leaf("CLUSTER","cluster"); printf("Found %s\n", yytext); return CLUSTER ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 82 "lexfinal.lex"
{ yylval.Node = add_leaf("PROCESSORS","processors"); printf("Found %s\n", yytext); return PROCESSORS ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "lexfinal.lex"
{ yylval.Node = add_leaf("TOPOLOGY","topology"); printf("Found %s\n", yytext); return TOPOLOGY ;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 84 "lexfinal.lex"
{ yylval.Node = add_leaf("LINK_BANDWIDTH","link_bandwidth"); printf("Found %s\n", yytext); return LINK_BANDWIDTH ;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "lexfinal.lex"
{ yylval.Node = add_leaf("LINK_CAPACITY","link_capacity"); printf("Found %s\n", yytext); return LINK_CAPACITY ;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 86 "lexfinal.lex"
{ yylval.Node = add_leaf("WAIT","wait"); printf("Found %s\n", yytext); return WAIT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 88 "lexfinal.lex"
{ yylval.Node = add_leaf("scheduler","SCHEDULER"); printf("Found %s\n", yytext); return SCHEDULER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 89 "lexfinal.lex"
{ yylval.Node = add_leaf("JOB_ARRAY","job_array"); printf("Found %s\n", yytext); return JOB_ARRAY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 90 "lexfinal.lex"
{ yylval.Node = add_leaf("PROCESSOR_ARRAY","processor_array"); printf("Found %s\n", yytext); return PROCESSOR_ARRAY; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 91 "lexfinal.lex"
{ yylval.Node = add_leaf("SET_JOB_AFFINITY","set_job_affinity"); printf("Found %s\n", yytext); return SET_JOB_AFFINITY; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 92 "lexfinal.lex"
{ yylval.Node = add_leaf("MAX_JOBS","max_jobs"); printf("Found %s\n", yytext); return MAX_JOBS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 93 "lexfinal.lex"
{ yylval.Node = add_leaf("GET_LOAD","get_load"); printf("Found %s\n", yytext); return GET_LOAD; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 94 "lexfinal.lex"
{ yylval.Node = add_leaf("SET_ALGO","set_algo"); printf("Found %s\n", yytext); return SET_ALGO; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 97 "lexfinal.lex"
{ yylval.Node = add_leaf("NUM",string(yytext)); printf("Found %s\n", yytext); return NUM; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 99 "lexfinal.lex"
{ yylval.Node = add_leaf("ID",string(yytext)); printf("Found ID %s\n", yytext); return ID ; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 101 "lexfinal.lex"
{}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 102 "lexfinal.lex"
{ yylineno++;	lineno++;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 104 "lexfinal.lex"
{printf("unexpected error\n");}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 106 "lexfinal.lex"
ECHO;
	YY_BREAK
#line 1560 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 424 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 424 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 423);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 106 "lexfinal.lex"




